---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Ensure Nginx is running and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

- name: Open port 80 and 443 in UFW
  ansible.builtin.ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - 'Nginx Full'
    - 'OpenSSH'
  when: ansible_facts['distribution'] == 'Ubuntu'

# Handlers
handlers:
  - name: Restart Nginx
    ansible.builtin.systemd:
      name: nginx
      state: restarted
