
version: '3.8'  # Make sure to specify a version

services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/yolomy
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"  # Change the host port to 27018
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:  # Define the volume here, not under services
